### ISSUE TITLE
Auto-Assign Copilot Workflow Fails with "HttpError: Not Found"

### ISSUE THREAD

**Issue by danielscholl** [danielscholl-osdu/osdu-mcp-server#53]
**Title:** Auto-Assign Copilot Workflow Fails with "HttpError: Not Found"

**Description:**

The GitHub Actions workflow `.github/workflows/copilot-assign.yml` fails with the following error:

```
Unhandled error: HttpError: Not Found
```

**Context:**  
- Workflow: [Auto-assign Copilot Issues](https://github.com/danielscholl-osdu/osdu-mcp-server/blob/7982794be3c043a139cbc11adb5b9954f2270149/.github/workflows/copilot-assign.yml)
- Job log: [Run 15219889488, Job 42813431228](https://github.com/danielscholl-osdu/osdu-mcp-server/actions/runs/15219889488/job/42813431228)
- The job fails when attempting to assign an issue to the `copilot` user or when creating a confirmation comment.

**Steps to Reproduce:**
1. Label an issue with `copilot`.
2. The workflow triggers and attempts to assign the issue to the `copilot` user and post a comment.

**Observed Behavior:**
- The job fails with `HttpError: Not Found`.

**Suspected Causes:**
- The `copilot` user may not exist or may not have permission to be assigned.
- The context passed to the API (`context.issue`) may be incomplete or incorrect.
- There could be a permissions issue with the workflow token.

**Suggested Solution:**
- Verify that the `copilot` user exists and can be assigned to issues in this repo.
- Enhance the workflow script with error handling and existence checks for the user.
- Ensure the GitHub token has `issues: write` permission.

**Relevant Code Snippet:**
```yaml
- name: Assign issue to Copilot
  uses: actions/github-script@v7
  with:
    script: |
      await github.rest.issues.addAssignees({
        ...context.issue,
        assignees: ['copilot']
      });
```
[View workflow file @ 7982794b](https://github.com/danielscholl-osdu/osdu-mcp-server/blob/7982794be3c043a139cbc11adb5b9954f2270149/.github/workflows/copilot-assign.yml)

---

Let me know if you want to add or adjust anything!
